import "./globals.css";
import type { Metadata } from "next";
import { ReduxProvider } from "@/redux/provider";
import { Montserrat } from "next/font/google";

import { Footer } from "@/components/Footer/Footer";
import { Header } from "@/components/Header/Header";

import { ThemeProvider } from "@mui/material";
import { theme } from "./theme";

export const revalidate = true;

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function asRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeProvider theme={theme}>
          <ReduxProvider>
            <Header />
            {children}
            <Footer />
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
